name: Project Iteration Management  # This shows in the Actions sidebar
run-name: "Move items to next iteration - ${{ github.event.schedule }}" # This shows in the run list

on:
  schedule:
    - cron: '30 23 * * 0' # Runs at 05:00 on Monday
  workflow_dispatch:   # Add this to test it manually right now!

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest
    steps:
    - uses: blombard/move-to-next-iteration@master
      with:
        owner: Ajinkyamoghe123
        number: 2
        token: ${{ secrets.PROJECT_PAT }}
        iteration-field: Sprint
        iteration: <current
        new-iteration: current
        statuses: 'Todo,In Progress,In Review'
